image:
  file: .devcontainer/Dockerfile

tasks:
  - init: bash .devcontainer/onCreateCommand.sh
    command: bash .devcontainer/postStartCommand.sh && bash && exit

ports:
  - port: 3000
    visibility: public

    